raphael: Drop some Prebuilt Packages
Our device has limited system partition size (legacy partition), so it's hard to ship heavy Gapps rom with all Xiaomi parts and Leica/miui camera , so better remove some prebuilt packages to avoid partition shortage errors.

error: Out of space? Out of inodes? The tree size of /home/mohammadkingoftheworld/ri sing/out/soong/.temp/tmpha95_k9r is 3740097536 bytes (3566 MB), with reserved space of bytes (0 MB). The max image size for filesystem files is 3698716672 bytes (3527 MB), out of a total partition size of 3758096384 bytes (3584 MB).

Signed-off-by: MohammadAlArabi <mohammadkingoftheworld@gmail.com>