raphael: fingerprint: Add missing import
device/xiaomi/raphael/fingerprint/BiometricsFingerprint.cpp:94:36: error: use of undeclared identifier 'O_RDONLY'
        int fd = open(FOD_UI_PATH, O_RDONLY);
                                   ^
referenced https://github.com/PixelDust-Twelve/android_device_google_contexthub/commit/a7dd2db05cb1beda4804a4feeabc43bfb85fefa4

Signed-off-by: SageOfD6Path <mail2anirban95@gmail.com>