raphael: Adapt TZ version assertions for A13
Traceback (most recent call last):
AddTrustZoneAssertion(info, info.input_zip)
m = re.search(r'require\s+version-trustzone\s*=\s*(\S+)', android_info)
TypeError: cannot use a string pattern on a bytes-like object
ninja failed with: exit status 1

Signed-off-by: Kujou Yuko <i@779.moe>
Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>